<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        DB::table('customer_property_definitions')->insertOrIgnore([
            [
                'key' => 'phone',
                'label' => 'Phone',
                'description' => 'Primary customer telephone number.',
                'type' => 'phone',
                'is_required' => true,
                'constraints' => json_encode(['max_length' => 32], JSON_THROW_ON_ERROR),
                'options' => null,
                'sort' => 100,
                'is_active' => true,
                'show_on_registration' => true,
                'show_on_checkout' => true,
                'show_on_account' => true,
                'show_on_invoice' => false,
                'customer_editable' => true,
                'staff_editable' => true,
                'internal_only' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'company_name',
                'label' => 'Company Name',
                'description' => 'Company associated with the customer.',
                'type' => 'text',
                'is_required' => false,
                'constraints' => json_encode(['max_length' => 255], JSON_THROW_ON_ERROR),
                'options' => null,
                'sort' => 101,
                'is_active' => true,
                'show_on_registration' => true,
                'show_on_checkout' => true,
                'show_on_account' => true,
                'show_on_invoice' => true,
                'customer_editable' => true,
                'staff_editable' => true,
                'internal_only' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'country',
                'label' => 'Country',
                'description' => 'Customer billing country.',
                'type' => 'country',
                'is_required' => true,
                'constraints' => null,
                'options' => null,
                'sort' => 102,
                'is_active' => true,
                'show_on_registration' => true,
                'show_on_checkout' => true,
                'show_on_account' => true,
                'show_on_invoice' => true,
                'customer_editable' => true,
                'staff_editable' => true,
                'internal_only' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'address',
                'label' => 'Address',
                'description' => 'Primary street address.',
                'type' => 'text',
                'is_required' => true,
                'constraints' => json_encode(['max_length' => 255], JSON_THROW_ON_ERROR),
                'options' => null,
                'sort' => 103,
                'is_active' => true,
                'show_on_registration' => true,
                'show_on_checkout' => true,
                'show_on_account' => true,
                'show_on_invoice' => true,
                'customer_editable' => true,
                'staff_editable' => true,
                'internal_only' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'address2',
                'label' => 'Address 2',
                'description' => 'Apartment, suite, unit, or other address details.',
                'type' => 'text',
                'is_required' => false,
                'constraints' => json_encode(['max_length' => 255], JSON_THROW_ON_ERROR),
                'options' => null,
                'sort' => 104,
                'is_active' => true,
                'show_on_registration' => true,
                'show_on_checkout' => true,
                'show_on_account' => true,
                'show_on_invoice' => false,
                'customer_editable' => true,
                'staff_editable' => true,
                'internal_only' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'city',
                'label' => 'City',
                'description' => 'Customer billing city.',
                'type' => 'text',
                'is_required' => true,
                'constraints' => json_encode(['max_length' => 255], JSON_THROW_ON_ERROR),
                'options' => null,
                'sort' => 105,
                'is_active' => true,
                'show_on_registration' => true,
                'show_on_checkout' => true,
                'show_on_account' => true,
                'show_on_invoice' => true,
                'customer_editable' => true,
                'staff_editable' => true,
                'internal_only' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'state',
                'label' => 'State',
                'description' => 'State, province, or region.',
                'type' => 'text',
                'is_required' => true,
                'constraints' => json_encode(['max_length' => 255], JSON_THROW_ON_ERROR),
                'options' => null,
                'sort' => 106,
                'is_active' => true,
                'show_on_registration' => true,
                'show_on_checkout' => true,
                'show_on_account' => true,
                'show_on_invoice' => true,
                'customer_editable' => true,
                'staff_editable' => true,
                'internal_only' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'zip',
                'label' => 'ZIP',
                'description' => 'ZIP or postal code.',
                'type' => 'text',
                'is_required' => true,
                'constraints' => json_encode(['max_length' => 32], JSON_THROW_ON_ERROR),
                'options' => null,
                'sort' => 107,
                'is_active' => true,
                'show_on_registration' => true,
                'show_on_checkout' => true,
                'show_on_account' => true,
                'show_on_invoice' => true,
                'customer_editable' => true,
                'staff_editable' => true,
                'internal_only' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }

    public function down(): void
    {
        DB::table('customer_property_definitions')
            ->whereIn('key', [
                'phone',
                'company_name',
                'country',
                'address',
                'address2',
                'city',
                'state',
                'zip',
            ])
            ->delete();
    }
};
