<?php

declare(strict_types=1);

use App\Agovena\Theme\ThemeSettingField;
use App\Agovena\Theme\ThemeSettingsSchema;

return new ThemeSettingsSchema([
    new ThemeSettingField(
        key: 'colors.accent',
        label: 'Accent color',
        type: 'color',
        default: '#1f4e46',
        group: 'branding',
        help: 'Primary buttons and interactive accents.',
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'colors.accent_hover',
        label: 'Accent hover',
        type: 'color',
        default: '#2a6b60',
        group: 'branding',
        sort: 20,
    ),
    new ThemeSettingField(
        key: 'colors.surface',
        label: 'Surface',
        type: 'color',
        default: '#ffffff',
        group: 'branding',
        sort: 30,
    ),
    new ThemeSettingField(
        key: 'colors.background',
        label: 'Background',
        type: 'color',
        default: '#f4f1ec',
        group: 'branding',
        sort: 40,
    ),
    new ThemeSettingField(
        key: 'colors.text',
        label: 'Text',
        type: 'color',
        default: '#1a1814',
        group: 'branding',
        sort: 50,
    ),
    new ThemeSettingField(
        key: 'header.announcement_enabled',
        label: 'Show announcement bar',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'header.announcement_text',
        label: 'Announcement text',
        type: 'string',
        default: 'Free shipping on orders over €50',
        group: 'header',
        sort: 20,
    ),
    new ThemeSettingField(
        key: 'header.announcement_link',
        label: 'Announcement link',
        type: 'string',
        default: '',
        group: 'header',
        help: 'Optional URL for the announcement bar.',
        sort: 30,
    ),
    new ThemeSettingField(
        key: 'header.search_enabled',
        label: 'Show search',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 40,
    ),
    new ThemeSettingField(
        key: 'header.sticky',
        label: 'Sticky header',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 50,
    ),
    new ThemeSettingField(
        key: 'header.show_account',
        label: 'Show account entry',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 60,
    ),
    new ThemeSettingField(
        key: 'catalog.products_per_row',
        label: 'Products per row',
        type: 'select',
        default: '3',
        group: 'catalog',
        options: ['2', '3', '4'],
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'catalog.image_ratio',
        label: 'Card image ratio',
        type: 'select',
        default: '4/3',
        group: 'catalog',
        options: ['1/1', '4/3', '3/4'],
        sort: 20,
    ),
    new ThemeSettingField(
        key: 'catalog.show_excerpt',
        label: 'Show description excerpt on cards',
        type: 'boolean',
        default: true,
        group: 'catalog',
        sort: 30,
    ),
    new ThemeSettingField(
        key: 'homepage.sections',
        label: 'Homepage sections',
        type: 'sections',
        default: [
            [
                'type' => 'hero',
                'eyebrow' => 'Welcome',
                'title' => 'Shop with clarity',
                'lede' => 'Quality products, clear pricing, and a simple shopping experience.',
                'cta_label' => 'Browse catalog',
                'cta_href' => '#catalog',
            ],
            [
                'type' => 'featured_categories',
                'title' => 'Shop by category',
                'lede' => 'Explore collections tailored to what you need.',
            ],
            [
                'type' => 'featured_products',
                'title' => 'Featured products',
                'lede' => 'A selection of what is available in the store right now.',
                'limit' => 8,
            ],
            [
                'type' => 'trust_strip',
                'items' => [
                    ['title' => 'Secure checkout', 'text' => 'Your order details stay protected.'],
                    ['title' => 'Clear pricing', 'text' => 'What you see is what you pay.'],
                    ['title' => 'Helpful support', 'text' => 'Reach out when you need a hand.'],
                ],
            ],
            [
                'type' => 'rich_text',
                'title' => 'About this store',
                'body' => 'This homepage is powered by Theme sections. Merchants will customize these blocks from Appearance → Customize.',
            ],
        ],
        group: 'homepage',
        sort: 10,
    ),
]);
