<?php

declare(strict_types=1);

use App\Agovena\Theme\ThemeSettingField;
use App\Agovena\Theme\ThemeSettingsSchema;

return new ThemeSettingsSchema([
    new ThemeSettingField(
        key: 'colors.accent',
        label: 'admin.appearance.theme_fields.colors.accent',
        type: 'color',
        default: '#155EEF',
        group: 'branding',
        help: 'admin.appearance.theme_field_help.colors.accent',
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'colors.accent_hover',
        label: 'admin.appearance.theme_fields.colors.accent_hover',
        type: 'color',
        default: '#1249C7',
        group: 'branding',
        sort: 20,
    ),
    new ThemeSettingField(
        key: 'colors.surface',
        label: 'admin.appearance.theme_fields.colors.surface',
        type: 'color',
        default: '#ffffff',
        group: 'branding',
        sort: 30,
    ),
    new ThemeSettingField(
        key: 'colors.background',
        label: 'admin.appearance.theme_fields.colors.background',
        type: 'color',
        default: '#f4f6fa',
        group: 'branding',
        sort: 40,
    ),
    new ThemeSettingField(
        key: 'colors.text',
        label: 'admin.appearance.theme_fields.colors.text',
        type: 'color',
        default: '#0f172a',
        group: 'branding',
        sort: 50,
    ),
    new ThemeSettingField(
        key: 'header.announcement_enabled',
        label: 'admin.appearance.theme_fields.header.announcement_enabled',
        type: 'boolean',
        default: true,
        group: 'header',
        help: 'admin.appearance.theme_field_help.header.announcement_enabled',
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'header.usp_items',
        label: 'admin.appearance.theme_fields.header.usp_items',
        type: 'usp_items',
        default: [
            [
                'text' => 'Free shipping from €25',
                'short' => 'Free shipping',
                'emphasis' => 'Free',
                'href' => '',
                'highlight' => false,
            ],
            [
                'text' => 'Easy returns within 30 days',
                'short' => 'Easy returns',
                'emphasis' => 'Easy',
                'href' => '',
                'highlight' => false,
            ],
            [
                'text' => 'Shop now',
                'short' => 'Shop',
                'emphasis' => '',
                'href' => '/#catalog',
                'highlight' => true,
            ],
        ],
        group: 'header',
        help: 'admin.appearance.theme_field_help.header.usp_items',
        sort: 20,
    ),
    new ThemeSettingField(
        key: 'header.search_enabled',
        label: 'admin.appearance.theme_fields.header.search_enabled',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 40,
    ),
    new ThemeSettingField(
        key: 'header.sticky',
        label: 'admin.appearance.theme_fields.header.sticky',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 50,
    ),
    new ThemeSettingField(
        key: 'header.show_account',
        label: 'admin.appearance.theme_fields.header.show_account',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 60,
    ),
    new ThemeSettingField(
        key: 'header.show_discovery_bar',
        label: 'admin.appearance.theme_fields.header.show_discovery_bar',
        type: 'boolean',
        default: true,
        group: 'header',
        help: 'admin.appearance.theme_field_help.header.show_discovery_bar',
        sort: 70,
    ),
    new ThemeSettingField(
        key: 'footer.tagline',
        label: 'admin.appearance.theme_fields.footer.tagline',
        type: 'string',
        default: 'Quality products, clear pricing, and a simple shopping experience.',
        group: 'footer',
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'catalog.products_per_row',
        label: 'admin.appearance.theme_fields.catalog.products_per_row',
        type: 'select',
        default: '4',
        group: 'catalog',
        options: ['2', '3', '4'],
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'catalog.image_ratio',
        label: 'admin.appearance.theme_fields.catalog.image_ratio',
        type: 'select',
        default: '1/1',
        group: 'catalog',
        options: ['1/1', '4/3', '3/4'],
        sort: 20,
    ),
    new ThemeSettingField(
        key: 'catalog.show_excerpt',
        label: 'admin.appearance.theme_fields.catalog.show_excerpt',
        type: 'boolean',
        default: false,
        group: 'catalog',
        sort: 30,
    ),
    new ThemeSettingField(
        key: 'homepage.sections',
        label: 'admin.appearance.theme_fields.homepage.sections',
        type: 'sections',
        default: [
            [
                'type' => 'hero',
                'eyebrow' => 'Self-hosted commerce',
                'title' => 'A sharper way to sell what you stock',
                'lede' => 'Phones, audio, and accessories with clear prices and a storefront you control.',
                'cta_label' => 'Shop the catalog',
                'cta_href' => '#catalog',
                'image' => 'demo/hero-promo.jpg',
            ],
            [
                'type' => 'featured_categories',
                'title' => 'Jump in',
                'lede' => 'Four doors into the catalog.',
            ],
            [
                'type' => 'featured_products',
                'title' => 'Featured products',
                'lede' => 'Popular picks from the catalog.',
                'limit' => 16,
            ],
            [
                'type' => 'promo_split',
                'title' => 'Built for every kind of shop',
                'body' => 'Physical goods, digital downloads, and services — presented with the same clear commerce experience.',
                'cta_label' => 'Browse catalog',
                'cta_href' => '#catalog',
                'image' => 'demo/promo-split.jpg',
            ],
            [
                'type' => 'trust_strip',
                'items' => [
                    ['title' => 'Secure checkout', 'text' => 'Protected order details.'],
                    ['title' => 'Clear pricing', 'text' => 'No surprise totals.'],
                    ['title' => 'Order confirmation', 'text' => 'Receipt by email.'],
                    ['title' => 'Helpful support', 'text' => 'Reach out anytime.'],
                ],
            ],
        ],
        group: 'homepage',
        sort: 10,
    ),
]);
