<?php

declare(strict_types=1);

use App\Agovena\Theme\ThemeSettingField;
use App\Agovena\Theme\ThemeSettingsSchema;

return new ThemeSettingsSchema([
    new ThemeSettingField(
        key: 'colors.accent',
        label: 'Accent color',
        type: 'color',
        default: '#155EEF',
        group: 'branding',
        help: 'Primary buttons and interactive accents.',
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'colors.accent_hover',
        label: 'Accent hover',
        type: 'color',
        default: '#1249C7',
        group: 'branding',
        sort: 20,
    ),
    new ThemeSettingField(
        key: 'colors.surface',
        label: 'Surface',
        type: 'color',
        default: '#ffffff',
        group: 'branding',
        sort: 30,
    ),
    new ThemeSettingField(
        key: 'colors.background',
        label: 'Background',
        type: 'color',
        default: '#f4f6fa',
        group: 'branding',
        sort: 40,
    ),
    new ThemeSettingField(
        key: 'colors.text',
        label: 'Text',
        type: 'color',
        default: '#0f172a',
        group: 'branding',
        sort: 50,
    ),
    new ThemeSettingField(
        key: 'header.announcement_enabled',
        label: 'Show announcement bar',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'header.announcement_text',
        label: 'Announcement text',
        type: 'string',
        default: 'Free shipping on orders over €50',
        group: 'header',
        sort: 20,
    ),
    new ThemeSettingField(
        key: 'header.announcement_link',
        label: 'Announcement link',
        type: 'string',
        default: '',
        group: 'header',
        help: 'Optional URL for the announcement bar.',
        sort: 30,
    ),
    new ThemeSettingField(
        key: 'header.search_enabled',
        label: 'Show search',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 40,
    ),
    new ThemeSettingField(
        key: 'header.sticky',
        label: 'Sticky header',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 50,
    ),
    new ThemeSettingField(
        key: 'header.show_account',
        label: 'Show account entry',
        type: 'boolean',
        default: true,
        group: 'header',
        sort: 60,
    ),
    new ThemeSettingField(
        key: 'header.show_discovery_bar',
        label: 'Show discovery navigation',
        type: 'boolean',
        default: true,
        group: 'header',
        help: 'Secondary bar for menu links and category discovery.',
        sort: 70,
    ),
    new ThemeSettingField(
        key: 'footer.tagline',
        label: 'Footer tagline',
        type: 'string',
        default: 'Quality products, clear pricing, and a simple shopping experience.',
        group: 'footer',
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'catalog.products_per_row',
        label: 'Products per row',
        type: 'select',
        default: '4',
        group: 'catalog',
        options: ['2', '3', '4'],
        sort: 10,
    ),
    new ThemeSettingField(
        key: 'catalog.image_ratio',
        label: 'Card image ratio',
        type: 'select',
        default: '1/1',
        group: 'catalog',
        options: ['1/1', '4/3', '3/4'],
        sort: 20,
    ),
    new ThemeSettingField(
        key: 'catalog.show_excerpt',
        label: 'Show description excerpt on cards',
        type: 'boolean',
        default: false,
        group: 'catalog',
        sort: 30,
    ),
    new ThemeSettingField(
        key: 'homepage.sections',
        label: 'Homepage sections',
        type: 'sections',
        default: [
            [
                'type' => 'hero',
                'eyebrow' => 'New arrivals',
                'title' => 'Phones and audio, clearly priced',
                'lede' => 'Browse smartphones, headphones, and accessories from one storefront.',
                'cta_label' => 'Shop featured',
                'cta_href' => '#catalog',
                'image' => 'demo/hero-promo.svg',
            ],
            [
                'type' => 'featured_categories',
                'title' => 'Shop by category',
                'lede' => 'Jump into a collection.',
            ],
            [
                'type' => 'featured_products',
                'title' => 'Featured products',
                'lede' => 'Popular picks from the catalog.',
                'limit' => 8,
            ],
            [
                'type' => 'promo_split',
                'title' => 'Built for every kind of shop',
                'body' => 'Physical goods, digital downloads, and services — presented with the same clear commerce experience.',
                'cta_label' => 'Browse catalog',
                'cta_href' => '#catalog',
                'image' => 'demo/promo-split.svg',
            ],
            [
                'type' => 'trust_strip',
                'items' => [
                    ['title' => 'Secure checkout', 'text' => 'Protected order details.'],
                    ['title' => 'Clear pricing', 'text' => 'No surprise totals.'],
                    ['title' => 'Order confirmation', 'text' => 'Receipt by email.'],
                    ['title' => 'Helpful support', 'text' => 'Reach out anytime.'],
                ],
            ],
        ],
        group: 'homepage',
        sort: 10,
    ),
]);
